steps:
- name: "gcr.io/cloud-builders/gcloud"
  timeout: "300s"
  args:
    - "compute"
    - "ssh"
    - "final-project-frontend"
    - "--zone=us-east1-d"
    - "--command"
    - |
      cd /var/www/html/CIS655-final-project &&
      git config --global --add safe.directory /var/www/html/CIS655-final-project &&
      git pull origin main &&
      sudo cp /var/www/html/CIS655-final-project/frontend/index.html /var/www/html &&
      sudo cp /var/www/html/CIS655-final-project/frontend/script.js /var/www/html &&
      sudo systemctl restart apache2
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
options:
  logging: CLOUD_LOGGING_ONLY