steps:
- name: "gcr.io/cloud-builders/gcloud"
  timeout: "300s"
  args:
    - "compute"
    - "ssh"
    - "final-project-frontend"
    - "--zone=us-east1-d"
    - "--command"
    - |
      cd /var/www/html/CIS655-final-project &&
      git config --global --add safe.directory /var/www/html/CIS655-final-project &&
      git pull origin main &&
      sudo cp /var/www/html/CIS655-final-project/frontend/index.html /var/www/html &&
      sudo cp /var/www/html/CIS655-final-project/frontend/script.js /var/www/html &&
      sudo systemctl restart apache2
- name: "gcr.io/cloud-builders/git"
  args: ["ls-files"]
- name: "gcr.io/cloud-builders/git"
  timeout: "300s"
  args:
    - "pull"
    - "origin"
    - "main"
  dir: "/workspace/CIS655-final-project"
- name: "gcr.io/cloud-builders/git"
  args: ["ls-files"]
  dir: "/workspace"
- name: "gcr.io/cloud-builders/gcloud"
  timeout: "300s"
  args:
    - "app"
    - "deploy"
    - "/workspace/backend/app.yaml"
    - "--verbosity=debug"
    - "--no-cache"
options:
  logging: CLOUD_LOGGING_ONLY