steps:
- name: "gcr.io/cloud-builders/gcloud"
  timeout: "300s"
  args:
    - "compute"
    - "ssh"
    - "final-project-frontend"
    - "--zone=us-east1-d"
    - "--command"
    - |
      cd /var/www/html/CIS655-final-project &&
      git pull origin main &&
      sudo mv /var/www/html/CIS655-final-project/frontend/index.html /var/www/html/ &&
      sudo systemctl restart apache2
options:
  logging: CLOUD_LOGGING_ONLY